"""removed pantry

Revision ID: 089a9a8622a5
Revises: 0069838bcc75
Create Date: 2019-11-29 12:48:24.757026

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '089a9a8622a5'
down_revision = '0069838bcc75'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_pantry_ingredient_id', table_name='pantry')
    op.drop_index('ix_pantry_ingredient_name', table_name='pantry')
    op.drop_index('ix_pantry_user_id', table_name='pantry')
    op.drop_table('pantry')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pantry',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=True),
    sa.Column('ingredient_id', sa.INTEGER(), nullable=True),
    sa.Column('ingredient_name', sa.VARCHAR(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_pantry_user_id', 'pantry', ['user_id'], unique=False)
    op.create_index('ix_pantry_ingredient_name', 'pantry', ['ingredient_name'], unique=False)
    op.create_index('ix_pantry_ingredient_id', 'pantry', ['ingredient_id'], unique=False)
    # ### end Alembic commands ###
