"""recreated pantry

Revision ID: 1164481ad511
Revises: 089a9a8622a5
Create Date: 2019-11-29 12:49:12.547904

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1164481ad511'
down_revision = '089a9a8622a5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pantry',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('ingredient_id', sa.Integer(), nullable=True),
    sa.Column('ingredient_name', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pantry_ingredient_id'), 'pantry', ['ingredient_id'], unique=False)
    op.create_index(op.f('ix_pantry_ingredient_name'), 'pantry', ['ingredient_name'], unique=False)
    op.create_index(op.f('ix_pantry_user_id'), 'pantry', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_pantry_user_id'), table_name='pantry')
    op.drop_index(op.f('ix_pantry_ingredient_name'), table_name='pantry')
    op.drop_index(op.f('ix_pantry_ingredient_id'), table_name='pantry')
    op.drop_table('pantry')
    # ### end Alembic commands ###
